// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWESOeajrKkukEvzJn6vKF_YoIIahBnuQ',
    appId: '1:1081752972552:web:a832104b22d7100eaf10bd',
    messagingSenderId: '1081752972552',
    projectId: 'plan-n-track-0',
    authDomain: 'plan-n-track-0.firebaseapp.com',
    storageBucket: 'plan-n-track-0.appspot.com',
    measurementId: 'G-V17NPW4853',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkzlrmdpSCiqePKLKiY2fUdp99UVi8bw',
    appId: '1:1081752972552:android:7b2fa874c42d2043af10bd',
    messagingSenderId: '1081752972552',
    projectId: 'plan-n-track-0',
    storageBucket: 'plan-n-track-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADpgprlX5S3o-izzSLj8YHXHQ0zgE7-v4',
    appId: '1:1081752972552:ios:4d691dc0d1762986af10bd',
    messagingSenderId: '1081752972552',
    projectId: 'plan-n-track-0',
    storageBucket: 'plan-n-track-0.appspot.com',
    iosClientId: '1081752972552-d37tmb3c9ic04a208o6q0bon1fcvvg3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.plan-n-track',
  );
}
